development:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  pool: 5
  database: <%= ENV['PGDATABASE'] %>